[package]
name = "deploy_rs"
version = "0.1.0"
authors = ["Diego Cabrejas <dcabrejas@icloud.com>"]

[dependencies]
toml_edit = "0.1.2"
ansi_term = "0.11.0"
docopt = "1.0.1"
serde = "1.0"
serde_derive = "1.0"
