# name of the software
name: Trappo Deployment Tool

project:
    version: 0.1.0
    download_url: https://github.com/dcabrejas/trappo

license:
    software: GPLv3 License
    software_url: https://www.gnu.org/licenses/gpl-3.0.en.html

links:
    header:
      - title: GitHub
        url: https://github.com/dcabrejas/trappo
    footer:
      - title: GitHub
        url: https://github.com/dcabrejas/trappo
      - title: Issues
        url: https://github.com/dcabrejas/trappo/issues?state=open

ui:
    header:
        color1: "#080331"
        color2: "#673051"
        trianglify: true

social:
    github:
        user: dcabrejas
        repo: trappo
    twitter:
        enabled: false
        via:
        hash:
        account:
    facebook:
        enabled: false
        profileUrl:

exclude:
    - Gemfile
    - Gemfile.lock
theme: jekyll-docs-theme

markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
